#!/bin/bash

# This will be the location of this script.
DIR="$(cd "$(dirname "$0")" && pwd)"

source "$DIR/bash-utils"

BREAD_INSTALL_DIR=`absolute_path $DIR/../lib/bread`

esy x BreadGen "$BREAD_INSTALL_DIR"
